package com.jzfq.retail.bean.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductCommentsQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public ProductCommentsQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("productComments.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("productComments.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("productComments.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("productComments.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("productComments.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("productComments.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("productComments.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("productComments.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("productComments.user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("productComments.user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("productComments.user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("productComments.user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("productComments.user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("productComments.user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("productComments.user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("productComments.user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("productComments.user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("productComments.user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("productComments.user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("productComments.user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("productComments.user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("productComments.user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("productComments.user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("productComments.user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("productComments.user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("productComments.user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("productComments.user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("productComments.user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("productComments.user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("productComments.grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("productComments.grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("productComments.grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("productComments.grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("productComments.grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("productComments.grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("productComments.grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("productComments.grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("productComments.grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("productComments.content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("productComments.content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("productComments.content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("productComments.content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("productComments.content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("productComments.content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("productComments.content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("productComments.content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("productComments.content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("productComments.content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("productComments.content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("productComments.content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("productComments.content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeIsNull() {
            addCriterion("productComments.seller_attitude is null");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeIsNotNull() {
            addCriterion("productComments.seller_attitude is not null");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeEqualTo(String value) {
            addCriterion("productComments.seller_attitude =", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeNotEqualTo(String value) {
            addCriterion("productComments.seller_attitude <>", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeGreaterThan(String value) {
            addCriterion("productComments.seller_attitude >", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.seller_attitude >=", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeLessThan(String value) {
            addCriterion("productComments.seller_attitude <", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeLessThanOrEqualTo(String value) {
            addCriterion("productComments.seller_attitude <=", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeLike(String value) {
            addCriterion("productComments.seller_attitude like", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeNotLike(String value) {
            addCriterion("productComments.seller_attitude not like", value, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeIn(List<String> values) {
            addCriterion("productComments.seller_attitude in", values, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeNotIn(List<String> values) {
            addCriterion("productComments.seller_attitude not in", values, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeBetween(String value1, String value2) {
            addCriterion("productComments.seller_attitude between", value1, value2, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeNotBetween(String value1, String value2) {
            addCriterion("productComments.seller_attitude not between", value1, value2, "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("productComments.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("productComments.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("productComments.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("productComments.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("productComments.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("productComments.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("productComments.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("productComments.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("productComments.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("productComments.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("productComments.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("productComments.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("productComments.product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("productComments.product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("productComments.product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("productComments.product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("productComments.product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("productComments.product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("productComments.product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("productComments.product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdIsNull() {
            addCriterion("productComments.product_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdIsNotNull() {
            addCriterion("productComments.product_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdEqualTo(Integer value) {
            addCriterion("productComments.product_goods_id =", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdNotEqualTo(Integer value) {
            addCriterion("productComments.product_goods_id <>", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdGreaterThan(Integer value) {
            addCriterion("productComments.product_goods_id >", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_goods_id >=", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdLessThan(Integer value) {
            addCriterion("productComments.product_goods_id <", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_goods_id <=", value, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdIn(List<Integer> values) {
            addCriterion("productComments.product_goods_id in", values, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdNotIn(List<Integer> values) {
            addCriterion("productComments.product_goods_id not in", values, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_goods_id between", value1, value2, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andProductGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_goods_id not between", value1, value2, "productGoodsId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("productComments.seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("productComments.seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Integer value) {
            addCriterion("productComments.seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Integer value) {
            addCriterion("productComments.seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Integer value) {
            addCriterion("productComments.seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Integer value) {
            addCriterion("productComments.seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<Integer> values) {
            addCriterion("productComments.seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<Integer> values) {
            addCriterion("productComments.seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andOrderSnIsNull() {
            addCriterion("productComments.order_sn is null");
            return (Criteria) this;
        }

        public Criteria andOrderSnIsNotNull() {
            addCriterion("productComments.order_sn is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSnEqualTo(String value) {
            addCriterion("productComments.order_sn =", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnNotEqualTo(String value) {
            addCriterion("productComments.order_sn <>", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnGreaterThan(String value) {
            addCriterion("productComments.order_sn >", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.order_sn >=", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnLessThan(String value) {
            addCriterion("productComments.order_sn <", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnLessThanOrEqualTo(String value) {
            addCriterion("productComments.order_sn <=", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnLike(String value) {
            addCriterion("productComments.order_sn like", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnNotLike(String value) {
            addCriterion("productComments.order_sn not like", value, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnIn(List<String> values) {
            addCriterion("productComments.order_sn in", values, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnNotIn(List<String> values) {
            addCriterion("productComments.order_sn not in", values, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnBetween(String value1, String value2) {
            addCriterion("productComments.order_sn between", value1, value2, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrderSnNotBetween(String value1, String value2) {
            addCriterion("productComments.order_sn not between", value1, value2, "orderSn");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdIsNull() {
            addCriterion("productComments.orders_product_id is null");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdIsNotNull() {
            addCriterion("productComments.orders_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdEqualTo(Integer value) {
            addCriterion("productComments.orders_product_id =", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdNotEqualTo(Integer value) {
            addCriterion("productComments.orders_product_id <>", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdGreaterThan(Integer value) {
            addCriterion("productComments.orders_product_id >", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.orders_product_id >=", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdLessThan(Integer value) {
            addCriterion("productComments.orders_product_id <", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.orders_product_id <=", value, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdIn(List<Integer> values) {
            addCriterion("productComments.orders_product_id in", values, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdNotIn(List<Integer> values) {
            addCriterion("productComments.orders_product_id not in", values, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.orders_product_id between", value1, value2, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andOrdersProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.orders_product_id not between", value1, value2, "ordersProductId");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNull() {
            addCriterion("productComments.reply_id is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNotNull() {
            addCriterion("productComments.reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdEqualTo(Integer value) {
            addCriterion("productComments.reply_id =", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotEqualTo(Integer value) {
            addCriterion("productComments.reply_id <>", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThan(Integer value) {
            addCriterion("productComments.reply_id >", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.reply_id >=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThan(Integer value) {
            addCriterion("productComments.reply_id <", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.reply_id <=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdIn(List<Integer> values) {
            addCriterion("productComments.reply_id in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotIn(List<Integer> values) {
            addCriterion("productComments.reply_id not in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.reply_id between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.reply_id not between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyNameIsNull() {
            addCriterion("productComments.reply_name is null");
            return (Criteria) this;
        }

        public Criteria andReplyNameIsNotNull() {
            addCriterion("productComments.reply_name is not null");
            return (Criteria) this;
        }

        public Criteria andReplyNameEqualTo(String value) {
            addCriterion("productComments.reply_name =", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameNotEqualTo(String value) {
            addCriterion("productComments.reply_name <>", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameGreaterThan(String value) {
            addCriterion("productComments.reply_name >", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.reply_name >=", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameLessThan(String value) {
            addCriterion("productComments.reply_name <", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameLessThanOrEqualTo(String value) {
            addCriterion("productComments.reply_name <=", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameLike(String value) {
            addCriterion("productComments.reply_name like", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameNotLike(String value) {
            addCriterion("productComments.reply_name not like", value, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameIn(List<String> values) {
            addCriterion("productComments.reply_name in", values, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameNotIn(List<String> values) {
            addCriterion("productComments.reply_name not in", values, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameBetween(String value1, String value2) {
            addCriterion("productComments.reply_name between", value1, value2, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyNameNotBetween(String value1, String value2) {
            addCriterion("productComments.reply_name not between", value1, value2, "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyContentIsNull() {
            addCriterion("productComments.reply_content is null");
            return (Criteria) this;
        }

        public Criteria andReplyContentIsNotNull() {
            addCriterion("productComments.reply_content is not null");
            return (Criteria) this;
        }

        public Criteria andReplyContentEqualTo(String value) {
            addCriterion("productComments.reply_content =", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotEqualTo(String value) {
            addCriterion("productComments.reply_content <>", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentGreaterThan(String value) {
            addCriterion("productComments.reply_content >", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentGreaterThanOrEqualTo(String value) {
            addCriterion("productComments.reply_content >=", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLessThan(String value) {
            addCriterion("productComments.reply_content <", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLessThanOrEqualTo(String value) {
            addCriterion("productComments.reply_content <=", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentLike(String value) {
            addCriterion("productComments.reply_content like", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotLike(String value) {
            addCriterion("productComments.reply_content not like", value, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentIn(List<String> values) {
            addCriterion("productComments.reply_content in", values, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotIn(List<String> values) {
            addCriterion("productComments.reply_content not in", values, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentBetween(String value1, String value2) {
            addCriterion("productComments.reply_content between", value1, value2, "replyContent");
            return (Criteria) this;
        }

        public Criteria andReplyContentNotBetween(String value1, String value2) {
            addCriterion("productComments.reply_content not between", value1, value2, "replyContent");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("productComments.state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("productComments.state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("productComments.state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("productComments.state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("productComments.state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("productComments.state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("productComments.state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("productComments.state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("productComments.state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("productComments.admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("productComments.admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("productComments.admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("productComments.admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("productComments.admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("productComments.admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("productComments.admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("productComments.admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("productComments.admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("productComments.description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("productComments.description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(Integer value) {
            addCriterion("productComments.description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(Integer value) {
            addCriterion("productComments.description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(Integer value) {
            addCriterion("productComments.description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(Integer value) {
            addCriterion("productComments.description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<Integer> values) {
            addCriterion("productComments.description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<Integer> values) {
            addCriterion("productComments.description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(Integer value1, Integer value2) {
            addCriterion("productComments.description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeIsNull() {
            addCriterion("productComments.service_attitude is null");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeIsNotNull() {
            addCriterion("productComments.service_attitude is not null");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeEqualTo(Integer value) {
            addCriterion("productComments.service_attitude =", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeNotEqualTo(Integer value) {
            addCriterion("productComments.service_attitude <>", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeGreaterThan(Integer value) {
            addCriterion("productComments.service_attitude >", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.service_attitude >=", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeLessThan(Integer value) {
            addCriterion("productComments.service_attitude <", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.service_attitude <=", value, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeIn(List<Integer> values) {
            addCriterion("productComments.service_attitude in", values, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeNotIn(List<Integer> values) {
            addCriterion("productComments.service_attitude not in", values, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeBetween(Integer value1, Integer value2) {
            addCriterion("productComments.service_attitude between", value1, value2, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andServiceAttitudeNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.service_attitude not between", value1, value2, "serviceAttitude");
            return (Criteria) this;
        }

        public Criteria andProductSpeedIsNull() {
            addCriterion("productComments.product_speed is null");
            return (Criteria) this;
        }

        public Criteria andProductSpeedIsNotNull() {
            addCriterion("productComments.product_speed is not null");
            return (Criteria) this;
        }

        public Criteria andProductSpeedEqualTo(Integer value) {
            addCriterion("productComments.product_speed =", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedNotEqualTo(Integer value) {
            addCriterion("productComments.product_speed <>", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedGreaterThan(Integer value) {
            addCriterion("productComments.product_speed >", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_speed >=", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedLessThan(Integer value) {
            addCriterion("productComments.product_speed <", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.product_speed <=", value, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedIn(List<Integer> values) {
            addCriterion("productComments.product_speed in", values, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedNotIn(List<Integer> values) {
            addCriterion("productComments.product_speed not in", values, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_speed between", value1, value2, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andProductSpeedNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.product_speed not between", value1, value2, "productSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedIsNull() {
            addCriterion("productComments.logistics_speed is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedIsNotNull() {
            addCriterion("productComments.logistics_speed is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedEqualTo(Integer value) {
            addCriterion("productComments.logistics_speed =", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedNotEqualTo(Integer value) {
            addCriterion("productComments.logistics_speed <>", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedGreaterThan(Integer value) {
            addCriterion("productComments.logistics_speed >", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.logistics_speed >=", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedLessThan(Integer value) {
            addCriterion("productComments.logistics_speed <", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.logistics_speed <=", value, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedIn(List<Integer> values) {
            addCriterion("productComments.logistics_speed in", values, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedNotIn(List<Integer> values) {
            addCriterion("productComments.logistics_speed not in", values, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedBetween(Integer value1, Integer value2) {
            addCriterion("productComments.logistics_speed between", value1, value2, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andLogisticsSpeedNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.logistics_speed not between", value1, value2, "logisticsSpeed");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeIsNull() {
            addCriterion("productComments.express_attitude is null");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeIsNotNull() {
            addCriterion("productComments.express_attitude is not null");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeEqualTo(Integer value) {
            addCriterion("productComments.express_attitude =", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeNotEqualTo(Integer value) {
            addCriterion("productComments.express_attitude <>", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeGreaterThan(Integer value) {
            addCriterion("productComments.express_attitude >", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeGreaterThanOrEqualTo(Integer value) {
            addCriterion("productComments.express_attitude >=", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeLessThan(Integer value) {
            addCriterion("productComments.express_attitude <", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeLessThanOrEqualTo(Integer value) {
            addCriterion("productComments.express_attitude <=", value, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeIn(List<Integer> values) {
            addCriterion("productComments.express_attitude in", values, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeNotIn(List<Integer> values) {
            addCriterion("productComments.express_attitude not in", values, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeBetween(Integer value1, Integer value2) {
            addCriterion("productComments.express_attitude between", value1, value2, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andExpressAttitudeNotBetween(Integer value1, Integer value2) {
            addCriterion("productComments.express_attitude not between", value1, value2, "expressAttitude");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(productComments.user_name) like", value.toUpperCase(), "userName");
            return (Criteria) this;
        }

        public Criteria andContentLikeInsensitive(String value) {
            addCriterion("upper(productComments.content) like", value.toUpperCase(), "content");
            return (Criteria) this;
        }

        public Criteria andSellerAttitudeLikeInsensitive(String value) {
            addCriterion("upper(productComments.seller_attitude) like", value.toUpperCase(), "sellerAttitude");
            return (Criteria) this;
        }

        public Criteria andOrderSnLikeInsensitive(String value) {
            addCriterion("upper(productComments.order_sn) like", value.toUpperCase(), "orderSn");
            return (Criteria) this;
        }

        public Criteria andReplyNameLikeInsensitive(String value) {
            addCriterion("upper(productComments.reply_name) like", value.toUpperCase(), "replyName");
            return (Criteria) this;
        }

        public Criteria andReplyContentLikeInsensitive(String value) {
            addCriterion("upper(productComments.reply_content) like", value.toUpperCase(), "replyContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_comments
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 27 16:29:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_comments
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}