package com.jzfq.retail.bean.domain;

import java.io.Serializable;
import java.util.Date;

public class PurchaseReturned implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.returned_code
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String returnedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.purchase_orders_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer purchaseOrdersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.supplier_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.product_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer productGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.received_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer receivedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.return_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer returnCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.unit
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer stockSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String stockSiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer stockAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String stockAddressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.is_all_return
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer isAllReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.is_change
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer isChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.create_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.reason
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_returned.return_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_returned
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.id
     *
     * @return the value of purchase_returned.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.id
     *
     * @param id the value for purchase_returned.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.returned_code
     *
     * @return the value of purchase_returned.returned_code
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getReturnedCode() {
        return returnedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.returned_code
     *
     * @param returnedCode the value for purchase_returned.returned_code
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setReturnedCode(String returnedCode) {
        this.returnedCode = returnedCode == null ? null : returnedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.purchase_orders_id
     *
     * @return the value of purchase_returned.purchase_orders_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getPurchaseOrdersId() {
        return purchaseOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.purchase_orders_id
     *
     * @param purchaseOrdersId the value for purchase_returned.purchase_orders_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setPurchaseOrdersId(Integer purchaseOrdersId) {
        this.purchaseOrdersId = purchaseOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.supplier_id
     *
     * @return the value of purchase_returned.supplier_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.supplier_id
     *
     * @param supplierId the value for purchase_returned.supplier_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.product_goods_id
     *
     * @return the value of purchase_returned.product_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getProductGoodsId() {
        return productGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.product_goods_id
     *
     * @param productGoodsId the value for purchase_returned.product_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setProductGoodsId(Integer productGoodsId) {
        this.productGoodsId = productGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.received_count
     *
     * @return the value of purchase_returned.received_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getReceivedCount() {
        return receivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.received_count
     *
     * @param receivedCount the value for purchase_returned.received_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setReceivedCount(Integer receivedCount) {
        this.receivedCount = receivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.return_count
     *
     * @return the value of purchase_returned.return_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getReturnCount() {
        return returnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.return_count
     *
     * @param returnCount the value for purchase_returned.return_count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setReturnCount(Integer returnCount) {
        this.returnCount = returnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.unit
     *
     * @return the value of purchase_returned.unit
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.unit
     *
     * @param unit the value for purchase_returned.unit
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.stock_site_id
     *
     * @return the value of purchase_returned.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getStockSiteId() {
        return stockSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.stock_site_id
     *
     * @param stockSiteId the value for purchase_returned.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockSiteId(Integer stockSiteId) {
        this.stockSiteId = stockSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.stock_site_name
     *
     * @return the value of purchase_returned.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getStockSiteName() {
        return stockSiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.stock_site_name
     *
     * @param stockSiteName the value for purchase_returned.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockSiteName(String stockSiteName) {
        this.stockSiteName = stockSiteName == null ? null : stockSiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.stock_address_id
     *
     * @return the value of purchase_returned.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getStockAddressId() {
        return stockAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.stock_address_id
     *
     * @param stockAddressId the value for purchase_returned.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockAddressId(Integer stockAddressId) {
        this.stockAddressId = stockAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.stock_address_name
     *
     * @return the value of purchase_returned.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getStockAddressName() {
        return stockAddressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.stock_address_name
     *
     * @param stockAddressName the value for purchase_returned.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockAddressName(String stockAddressName) {
        this.stockAddressName = stockAddressName == null ? null : stockAddressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.is_all_return
     *
     * @return the value of purchase_returned.is_all_return
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getIsAllReturn() {
        return isAllReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.is_all_return
     *
     * @param isAllReturn the value for purchase_returned.is_all_return
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setIsAllReturn(Integer isAllReturn) {
        this.isAllReturn = isAllReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.is_change
     *
     * @return the value of purchase_returned.is_change
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getIsChange() {
        return isChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.is_change
     *
     * @param isChange the value for purchase_returned.is_change
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setIsChange(Integer isChange) {
        this.isChange = isChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.create_time
     *
     * @return the value of purchase_returned.create_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.create_time
     *
     * @param createTime the value for purchase_returned.create_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.reason
     *
     * @return the value of purchase_returned.reason
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.reason
     *
     * @param reason the value for purchase_returned.reason
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_returned.return_time
     *
     * @return the value of purchase_returned.return_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_returned.return_time
     *
     * @param returnTime the value for purchase_returned.return_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_returned
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PurchaseReturned other = (PurchaseReturned) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReturnedCode() == null ? other.getReturnedCode() == null : this.getReturnedCode().equals(other.getReturnedCode()))
            && (this.getPurchaseOrdersId() == null ? other.getPurchaseOrdersId() == null : this.getPurchaseOrdersId().equals(other.getPurchaseOrdersId()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getProductGoodsId() == null ? other.getProductGoodsId() == null : this.getProductGoodsId().equals(other.getProductGoodsId()))
            && (this.getReceivedCount() == null ? other.getReceivedCount() == null : this.getReceivedCount().equals(other.getReceivedCount()))
            && (this.getReturnCount() == null ? other.getReturnCount() == null : this.getReturnCount().equals(other.getReturnCount()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getStockSiteId() == null ? other.getStockSiteId() == null : this.getStockSiteId().equals(other.getStockSiteId()))
            && (this.getStockSiteName() == null ? other.getStockSiteName() == null : this.getStockSiteName().equals(other.getStockSiteName()))
            && (this.getStockAddressId() == null ? other.getStockAddressId() == null : this.getStockAddressId().equals(other.getStockAddressId()))
            && (this.getStockAddressName() == null ? other.getStockAddressName() == null : this.getStockAddressName().equals(other.getStockAddressName()))
            && (this.getIsAllReturn() == null ? other.getIsAllReturn() == null : this.getIsAllReturn().equals(other.getIsAllReturn()))
            && (this.getIsChange() == null ? other.getIsChange() == null : this.getIsChange().equals(other.getIsChange()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getReturnTime() == null ? other.getReturnTime() == null : this.getReturnTime().equals(other.getReturnTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_returned
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReturnedCode() == null) ? 0 : getReturnedCode().hashCode());
        result = prime * result + ((getPurchaseOrdersId() == null) ? 0 : getPurchaseOrdersId().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getProductGoodsId() == null) ? 0 : getProductGoodsId().hashCode());
        result = prime * result + ((getReceivedCount() == null) ? 0 : getReceivedCount().hashCode());
        result = prime * result + ((getReturnCount() == null) ? 0 : getReturnCount().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getStockSiteId() == null) ? 0 : getStockSiteId().hashCode());
        result = prime * result + ((getStockSiteName() == null) ? 0 : getStockSiteName().hashCode());
        result = prime * result + ((getStockAddressId() == null) ? 0 : getStockAddressId().hashCode());
        result = prime * result + ((getStockAddressName() == null) ? 0 : getStockAddressName().hashCode());
        result = prime * result + ((getIsAllReturn() == null) ? 0 : getIsAllReturn().hashCode());
        result = prime * result + ((getIsChange() == null) ? 0 : getIsChange().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getReturnTime() == null) ? 0 : getReturnTime().hashCode());
        return result;
    }
}