package com.jzfq.retail.bean.domain;

import java.io.Serializable;
import java.util.Date;

public class PurchaseCollectGoodsInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.purchase_collect_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer purchaseCollectGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.into_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Date intoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.sn
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer stockSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String stockSiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private Integer stockAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String stockAddressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_collect_goods_info.remark
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.id
     *
     * @return the value of purchase_collect_goods_info.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.id
     *
     * @param id the value for purchase_collect_goods_info.id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.purchase_collect_goods_id
     *
     * @return the value of purchase_collect_goods_info.purchase_collect_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getPurchaseCollectGoodsId() {
        return purchaseCollectGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.purchase_collect_goods_id
     *
     * @param purchaseCollectGoodsId the value for purchase_collect_goods_info.purchase_collect_goods_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setPurchaseCollectGoodsId(Integer purchaseCollectGoodsId) {
        this.purchaseCollectGoodsId = purchaseCollectGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.into_time
     *
     * @return the value of purchase_collect_goods_info.into_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Date getIntoTime() {
        return intoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.into_time
     *
     * @param intoTime the value for purchase_collect_goods_info.into_time
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setIntoTime(Date intoTime) {
        this.intoTime = intoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.sn
     *
     * @return the value of purchase_collect_goods_info.sn
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.sn
     *
     * @param sn the value for purchase_collect_goods_info.sn
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.count
     *
     * @return the value of purchase_collect_goods_info.count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.count
     *
     * @param count the value for purchase_collect_goods_info.count
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.stock_site_id
     *
     * @return the value of purchase_collect_goods_info.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getStockSiteId() {
        return stockSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.stock_site_id
     *
     * @param stockSiteId the value for purchase_collect_goods_info.stock_site_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockSiteId(Integer stockSiteId) {
        this.stockSiteId = stockSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.stock_site_name
     *
     * @return the value of purchase_collect_goods_info.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getStockSiteName() {
        return stockSiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.stock_site_name
     *
     * @param stockSiteName the value for purchase_collect_goods_info.stock_site_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockSiteName(String stockSiteName) {
        this.stockSiteName = stockSiteName == null ? null : stockSiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.stock_address_id
     *
     * @return the value of purchase_collect_goods_info.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public Integer getStockAddressId() {
        return stockAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.stock_address_id
     *
     * @param stockAddressId the value for purchase_collect_goods_info.stock_address_id
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockAddressId(Integer stockAddressId) {
        this.stockAddressId = stockAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.stock_address_name
     *
     * @return the value of purchase_collect_goods_info.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getStockAddressName() {
        return stockAddressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.stock_address_name
     *
     * @param stockAddressName the value for purchase_collect_goods_info.stock_address_name
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setStockAddressName(String stockAddressName) {
        this.stockAddressName = stockAddressName == null ? null : stockAddressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_collect_goods_info.remark
     *
     * @return the value of purchase_collect_goods_info.remark
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_collect_goods_info.remark
     *
     * @param remark the value for purchase_collect_goods_info.remark
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PurchaseCollectGoodsInfo other = (PurchaseCollectGoodsInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPurchaseCollectGoodsId() == null ? other.getPurchaseCollectGoodsId() == null : this.getPurchaseCollectGoodsId().equals(other.getPurchaseCollectGoodsId()))
            && (this.getIntoTime() == null ? other.getIntoTime() == null : this.getIntoTime().equals(other.getIntoTime()))
            && (this.getSn() == null ? other.getSn() == null : this.getSn().equals(other.getSn()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getStockSiteId() == null ? other.getStockSiteId() == null : this.getStockSiteId().equals(other.getStockSiteId()))
            && (this.getStockSiteName() == null ? other.getStockSiteName() == null : this.getStockSiteName().equals(other.getStockSiteName()))
            && (this.getStockAddressId() == null ? other.getStockAddressId() == null : this.getStockAddressId().equals(other.getStockAddressId()))
            && (this.getStockAddressName() == null ? other.getStockAddressName() == null : this.getStockAddressName().equals(other.getStockAddressName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPurchaseCollectGoodsId() == null) ? 0 : getPurchaseCollectGoodsId().hashCode());
        result = prime * result + ((getIntoTime() == null) ? 0 : getIntoTime().hashCode());
        result = prime * result + ((getSn() == null) ? 0 : getSn().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getStockSiteId() == null) ? 0 : getStockSiteId().hashCode());
        result = prime * result + ((getStockSiteName() == null) ? 0 : getStockSiteName().hashCode());
        result = prime * result + ((getStockAddressId() == null) ? 0 : getStockAddressId().hashCode());
        result = prime * result + ((getStockAddressName() == null) ? 0 : getStockAddressName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}