package com.jzfq.retail.bean.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SellerApproval implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.seller_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.seller_code
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String sellerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.order_no
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private BigDecimal quota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.available_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private BigDecimal availableQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.first_limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private BigDecimal firstLimitQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private BigDecimal limitQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.approval_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Date approvalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.seller_status
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String sellerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.create_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.create_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.create_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.update_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.update_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.update_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_approval.serial_number
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller_approval
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.id
     *
     * @return the value of seller_approval.id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.id
     *
     * @param id the value for seller_approval.id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.seller_id
     *
     * @return the value of seller_approval.seller_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.seller_id
     *
     * @param sellerId the value for seller_approval.seller_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.seller_code
     *
     * @return the value of seller_approval.seller_code
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getSellerCode() {
        return sellerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.seller_code
     *
     * @param sellerCode the value for seller_approval.seller_code
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setSellerCode(String sellerCode) {
        this.sellerCode = sellerCode == null ? null : sellerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.order_no
     *
     * @return the value of seller_approval.order_no
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.order_no
     *
     * @param orderNo the value for seller_approval.order_no
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.quota
     *
     * @return the value of seller_approval.quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public BigDecimal getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.quota
     *
     * @param quota the value for seller_approval.quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setQuota(BigDecimal quota) {
        this.quota = quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.available_quota
     *
     * @return the value of seller_approval.available_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public BigDecimal getAvailableQuota() {
        return availableQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.available_quota
     *
     * @param availableQuota the value for seller_approval.available_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setAvailableQuota(BigDecimal availableQuota) {
        this.availableQuota = availableQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.first_limit_quota
     *
     * @return the value of seller_approval.first_limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public BigDecimal getFirstLimitQuota() {
        return firstLimitQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.first_limit_quota
     *
     * @param firstLimitQuota the value for seller_approval.first_limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setFirstLimitQuota(BigDecimal firstLimitQuota) {
        this.firstLimitQuota = firstLimitQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.limit_quota
     *
     * @return the value of seller_approval.limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public BigDecimal getLimitQuota() {
        return limitQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.limit_quota
     *
     * @param limitQuota the value for seller_approval.limit_quota
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setLimitQuota(BigDecimal limitQuota) {
        this.limitQuota = limitQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.approval_time
     *
     * @return the value of seller_approval.approval_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.approval_time
     *
     * @param approvalTime the value for seller_approval.approval_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.seller_status
     *
     * @return the value of seller_approval.seller_status
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getSellerStatus() {
        return sellerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.seller_status
     *
     * @param sellerStatus the value for seller_approval.seller_status
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setSellerStatus(String sellerStatus) {
        this.sellerStatus = sellerStatus == null ? null : sellerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.create_time
     *
     * @return the value of seller_approval.create_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.create_time
     *
     * @param createTime the value for seller_approval.create_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.create_name
     *
     * @return the value of seller_approval.create_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.create_name
     *
     * @param createName the value for seller_approval.create_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.create_user_id
     *
     * @return the value of seller_approval.create_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.create_user_id
     *
     * @param createUserId the value for seller_approval.create_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.update_time
     *
     * @return the value of seller_approval.update_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.update_time
     *
     * @param updateTime the value for seller_approval.update_time
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.update_name
     *
     * @return the value of seller_approval.update_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.update_name
     *
     * @param updateName the value for seller_approval.update_name
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.update_user_id
     *
     * @return the value of seller_approval.update_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.update_user_id
     *
     * @param updateUserId the value for seller_approval.update_user_id
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_approval.serial_number
     *
     * @return the value of seller_approval.serial_number
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_approval.serial_number
     *
     * @param serialNumber the value for seller_approval.serial_number
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_approval
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SellerApproval other = (SellerApproval) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSellerId() == null ? other.getSellerId() == null : this.getSellerId().equals(other.getSellerId()))
            && (this.getSellerCode() == null ? other.getSellerCode() == null : this.getSellerCode().equals(other.getSellerCode()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getQuota() == null ? other.getQuota() == null : this.getQuota().equals(other.getQuota()))
            && (this.getAvailableQuota() == null ? other.getAvailableQuota() == null : this.getAvailableQuota().equals(other.getAvailableQuota()))
            && (this.getFirstLimitQuota() == null ? other.getFirstLimitQuota() == null : this.getFirstLimitQuota().equals(other.getFirstLimitQuota()))
            && (this.getLimitQuota() == null ? other.getLimitQuota() == null : this.getLimitQuota().equals(other.getLimitQuota()))
            && (this.getApprovalTime() == null ? other.getApprovalTime() == null : this.getApprovalTime().equals(other.getApprovalTime()))
            && (this.getSellerStatus() == null ? other.getSellerStatus() == null : this.getSellerStatus().equals(other.getSellerStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateName() == null ? other.getCreateName() == null : this.getCreateName().equals(other.getCreateName()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateName() == null ? other.getUpdateName() == null : this.getUpdateName().equals(other.getUpdateName()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getSerialNumber() == null ? other.getSerialNumber() == null : this.getSerialNumber().equals(other.getSerialNumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_approval
     *
     * @mbggenerated Wed Jul 18 14:16:10 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSellerId() == null) ? 0 : getSellerId().hashCode());
        result = prime * result + ((getSellerCode() == null) ? 0 : getSellerCode().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getQuota() == null) ? 0 : getQuota().hashCode());
        result = prime * result + ((getAvailableQuota() == null) ? 0 : getAvailableQuota().hashCode());
        result = prime * result + ((getFirstLimitQuota() == null) ? 0 : getFirstLimitQuota().hashCode());
        result = prime * result + ((getLimitQuota() == null) ? 0 : getLimitQuota().hashCode());
        result = prime * result + ((getApprovalTime() == null) ? 0 : getApprovalTime().hashCode());
        result = prime * result + ((getSellerStatus() == null) ? 0 : getSellerStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateName() == null) ? 0 : getCreateName().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateName() == null) ? 0 : getUpdateName().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getSerialNumber() == null) ? 0 : getSerialNumber().hashCode());
        return result;
    }
}