package com.jzfq.retail.bean.domain;

import java.io.Serializable;
import java.util.Date;

public class SellerSingleCredit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.seller_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.is_open
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Integer isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.credit_limit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Long creditLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.create_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.update_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Integer updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.create_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.update_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.create_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_single_credit.update_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller_single_credit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.id
     *
     * @return the value of seller_single_credit.id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.id
     *
     * @param id the value for seller_single_credit.id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.seller_id
     *
     * @return the value of seller_single_credit.seller_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.seller_id
     *
     * @param sellerId the value for seller_single_credit.seller_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.is_open
     *
     * @return the value of seller_single_credit.is_open
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.is_open
     *
     * @param isOpen the value for seller_single_credit.is_open
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.credit_limit
     *
     * @return the value of seller_single_credit.credit_limit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Long getCreditLimit() {
        return creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.credit_limit
     *
     * @param creditLimit the value for seller_single_credit.credit_limit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setCreditLimit(Long creditLimit) {
        this.creditLimit = creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.create_id
     *
     * @return the value of seller_single_credit.create_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.create_id
     *
     * @param createId the value for seller_single_credit.create_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.update_id
     *
     * @return the value of seller_single_credit.update_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.update_id
     *
     * @param updateId the value for seller_single_credit.update_id
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.create_user
     *
     * @return the value of seller_single_credit.create_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.create_user
     *
     * @param createUser the value for seller_single_credit.create_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.update_user
     *
     * @return the value of seller_single_credit.update_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.update_user
     *
     * @param updateUser the value for seller_single_credit.update_user
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.create_time
     *
     * @return the value of seller_single_credit.create_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.create_time
     *
     * @param createTime the value for seller_single_credit.create_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_single_credit.update_time
     *
     * @return the value of seller_single_credit.update_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_single_credit.update_time
     *
     * @param updateTime the value for seller_single_credit.update_time
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_single_credit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SellerSingleCredit other = (SellerSingleCredit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSellerId() == null ? other.getSellerId() == null : this.getSellerId().equals(other.getSellerId()))
            && (this.getIsOpen() == null ? other.getIsOpen() == null : this.getIsOpen().equals(other.getIsOpen()))
            && (this.getCreditLimit() == null ? other.getCreditLimit() == null : this.getCreditLimit().equals(other.getCreditLimit()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_single_credit
     *
     * @mbggenerated Thu Jul 05 09:37:06 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSellerId() == null) ? 0 : getSellerId().hashCode());
        result = prime * result + ((getIsOpen() == null) ? 0 : getIsOpen().hashCode());
        result = prime * result + ((getCreditLimit() == null) ? 0 : getCreditLimit().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}