package com.jzfq.retail.bean.domain;

import java.io.Serializable;

public class StockStatus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_status.id
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_status.code
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_status.is_available
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private Boolean isAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_status.is_movable
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private Boolean isMovable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_status.is_excessive
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private Boolean isExcessive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_status
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_status.id
     *
     * @return the value of stock_status.id
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_status.id
     *
     * @param id the value for stock_status.id
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_status.code
     *
     * @return the value of stock_status.code
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_status.code
     *
     * @param code the value for stock_status.code
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_status.is_available
     *
     * @return the value of stock_status.is_available
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public Boolean getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_status.is_available
     *
     * @param isAvailable the value for stock_status.is_available
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_status.is_movable
     *
     * @return the value of stock_status.is_movable
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public Boolean getIsMovable() {
        return isMovable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_status.is_movable
     *
     * @param isMovable the value for stock_status.is_movable
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public void setIsMovable(Boolean isMovable) {
        this.isMovable = isMovable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_status.is_excessive
     *
     * @return the value of stock_status.is_excessive
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public Boolean getIsExcessive() {
        return isExcessive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_status.is_excessive
     *
     * @param isExcessive the value for stock_status.is_excessive
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    public void setIsExcessive(Boolean isExcessive) {
        this.isExcessive = isExcessive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_status
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockStatus other = (StockStatus) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getIsAvailable() == null ? other.getIsAvailable() == null : this.getIsAvailable().equals(other.getIsAvailable()))
            && (this.getIsMovable() == null ? other.getIsMovable() == null : this.getIsMovable().equals(other.getIsMovable()))
            && (this.getIsExcessive() == null ? other.getIsExcessive() == null : this.getIsExcessive().equals(other.getIsExcessive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_status
     *
     * @mbggenerated Thu Aug 02 14:59:40 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getIsAvailable() == null) ? 0 : getIsAvailable().hashCode());
        result = prime * result + ((getIsMovable() == null) ? 0 : getIsMovable().hashCode());
        result = prime * result + ((getIsExcessive() == null) ? 0 : getIsExcessive().hashCode());
        return result;
    }
}