package com.jzfq.retail.bean.vo.req;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrdersBaseReq implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.order_sn
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    /*@NotEmpty(message="订单号不能为空")
    @Length(min = 1, max = 20, message = "请输入正确的订单号")*/
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.order_type
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */

   // @NotEmpty(message="订单类型不能为空，1、普通订单，2、限时抢购订单，3、团购订单，4、竞价定金订单，5、竞价尾款订单，6、积分商城订单，7.企业购订单")

    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.seller_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */

    private Integer sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.seller_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.member_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */

    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.member_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.order_state
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.money_order
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private BigDecimal moneyOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.downpayment_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private BigDecimal downpaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.monthly_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private BigDecimal monthlyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.deliver_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date deliverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.finish_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.source
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.codconfirm_remark
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String codconfirmRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.create_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.update_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.is_full_payment
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Integer isFullPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.picking_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date pickingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.supplier
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.staging_money
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private BigDecimal stagingMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.logistics_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String logisticsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.logistics_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String logisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.logistics_number
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private String logisticsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.is_del
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_base.codconfirm_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private Date codconfirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders_base
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.id
     *
     * @return the value of orders_base.id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.id
     *
     * @param id the value for orders_base.id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.order_sn
     *
     * @return the value of orders_base.order_sn
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.order_sn
     *
     * @param orderSn the value for orders_base.order_sn
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.order_type
     *
     * @return the value of orders_base.order_type
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.order_type
     *
     * @param orderType the value for orders_base.order_type
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.seller_id
     *
     * @return the value of orders_base.seller_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.seller_id
     *
     * @param sellerId the value for orders_base.seller_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.seller_name
     *
     * @return the value of orders_base.seller_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.seller_name
     *
     * @param sellerName the value for orders_base.seller_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.member_id
     *
     * @return the value of orders_base.member_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.member_id
     *
     * @param memberId the value for orders_base.member_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.member_name
     *
     * @return the value of orders_base.member_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.member_name
     *
     * @param memberName the value for orders_base.member_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.order_state
     *
     * @return the value of orders_base.order_state
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.order_state
     *
     * @param orderState the value for orders_base.order_state
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.money_order
     *
     * @return the value of orders_base.money_order
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public BigDecimal getMoneyOrder() {
        return moneyOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.money_order
     *
     * @param moneyOrder the value for orders_base.money_order
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setMoneyOrder(BigDecimal moneyOrder) {
        this.moneyOrder = moneyOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.downpayment_amount
     *
     * @return the value of orders_base.downpayment_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public BigDecimal getDownpaymentAmount() {
        return downpaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.downpayment_amount
     *
     * @param downpaymentAmount the value for orders_base.downpayment_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setDownpaymentAmount(BigDecimal downpaymentAmount) {
        this.downpaymentAmount = downpaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.monthly_amount
     *
     * @return the value of orders_base.monthly_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public BigDecimal getMonthlyAmount() {
        return monthlyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.monthly_amount
     *
     * @param monthlyAmount the value for orders_base.monthly_amount
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setMonthlyAmount(BigDecimal monthlyAmount) {
        this.monthlyAmount = monthlyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.deliver_time
     *
     * @return the value of orders_base.deliver_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.deliver_time
     *
     * @param deliverTime the value for orders_base.deliver_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setDeliverTime(Date deliverTime) {
        this.deliverTime = deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.finish_time
     *
     * @return the value of orders_base.finish_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.finish_time
     *
     * @param finishTime the value for orders_base.finish_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.source
     *
     * @return the value of orders_base.source
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.source
     *
     * @param source the value for orders_base.source
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.codconfirm_remark
     *
     * @return the value of orders_base.codconfirm_remark
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getCodconfirmRemark() {
        return codconfirmRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.codconfirm_remark
     *
     * @param codconfirmRemark the value for orders_base.codconfirm_remark
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setCodconfirmRemark(String codconfirmRemark) {
        this.codconfirmRemark = codconfirmRemark == null ? null : codconfirmRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.create_time
     *
     * @return the value of orders_base.create_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.create_time
     *
     * @param createTime the value for orders_base.create_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.update_time
     *
     * @return the value of orders_base.update_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.update_time
     *
     * @param updateTime the value for orders_base.update_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.is_full_payment
     *
     * @return the value of orders_base.is_full_payment
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getIsFullPayment() {
        return isFullPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.is_full_payment
     *
     * @param isFullPayment the value for orders_base.is_full_payment
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setIsFullPayment(Integer isFullPayment) {
        this.isFullPayment = isFullPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.picking_time
     *
     * @return the value of orders_base.picking_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getPickingTime() {
        return pickingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.picking_time
     *
     * @param pickingTime the value for orders_base.picking_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setPickingTime(Date pickingTime) {
        this.pickingTime = pickingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.supplier
     *
     * @return the value of orders_base.supplier
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.supplier
     *
     * @param supplier the value for orders_base.supplier
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.staging_money
     *
     * @return the value of orders_base.staging_money
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public BigDecimal getStagingMoney() {
        return stagingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.staging_money
     *
     * @param stagingMoney the value for orders_base.staging_money
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setStagingMoney(BigDecimal stagingMoney) {
        this.stagingMoney = stagingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.logistics_name
     *
     * @return the value of orders_base.logistics_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.logistics_name
     *
     * @param logisticsName the value for orders_base.logistics_name
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.logistics_id
     *
     * @return the value of orders_base.logistics_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getLogisticsId() {
        return logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.logistics_id
     *
     * @param logisticsId the value for orders_base.logistics_id
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setLogisticsId(String logisticsId) {
        this.logisticsId = logisticsId == null ? null : logisticsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.logistics_number
     *
     * @return the value of orders_base.logistics_number
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public String getLogisticsNumber() {
        return logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.logistics_number
     *
     * @param logisticsNumber the value for orders_base.logistics_number
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setLogisticsNumber(String logisticsNumber) {
        this.logisticsNumber = logisticsNumber == null ? null : logisticsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.is_del
     *
     * @return the value of orders_base.is_del
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.is_del
     *
     * @param isDel the value for orders_base.is_del
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_base.codconfirm_time
     *
     * @return the value of orders_base.codconfirm_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public Date getCodconfirmTime() {
        return codconfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_base.codconfirm_time
     *
     * @param codconfirmTime the value for orders_base.codconfirm_time
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    public void setCodconfirmTime(Date codconfirmTime) {
        this.codconfirmTime = codconfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_base
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrdersBaseReq other = (OrdersBaseReq) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getOrderType() == null ? other.getOrderType() == null : this.getOrderType().equals(other.getOrderType()))
            && (this.getSellerId() == null ? other.getSellerId() == null : this.getSellerId().equals(other.getSellerId()))
            && (this.getSellerName() == null ? other.getSellerName() == null : this.getSellerName().equals(other.getSellerName()))
            && (this.getMemberId() == null ? other.getMemberId() == null : this.getMemberId().equals(other.getMemberId()))
            && (this.getMemberName() == null ? other.getMemberName() == null : this.getMemberName().equals(other.getMemberName()))
            && (this.getOrderState() == null ? other.getOrderState() == null : this.getOrderState().equals(other.getOrderState()))
            && (this.getMoneyOrder() == null ? other.getMoneyOrder() == null : this.getMoneyOrder().equals(other.getMoneyOrder()))
            && (this.getDownpaymentAmount() == null ? other.getDownpaymentAmount() == null : this.getDownpaymentAmount().equals(other.getDownpaymentAmount()))
            && (this.getMonthlyAmount() == null ? other.getMonthlyAmount() == null : this.getMonthlyAmount().equals(other.getMonthlyAmount()))
            && (this.getDeliverTime() == null ? other.getDeliverTime() == null : this.getDeliverTime().equals(other.getDeliverTime()))
            && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getCodconfirmRemark() == null ? other.getCodconfirmRemark() == null : this.getCodconfirmRemark().equals(other.getCodconfirmRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getIsFullPayment() == null ? other.getIsFullPayment() == null : this.getIsFullPayment().equals(other.getIsFullPayment()))
            && (this.getPickingTime() == null ? other.getPickingTime() == null : this.getPickingTime().equals(other.getPickingTime()))
            && (this.getSupplier() == null ? other.getSupplier() == null : this.getSupplier().equals(other.getSupplier()))
            && (this.getStagingMoney() == null ? other.getStagingMoney() == null : this.getStagingMoney().equals(other.getStagingMoney()))
            && (this.getLogisticsName() == null ? other.getLogisticsName() == null : this.getLogisticsName().equals(other.getLogisticsName()))
            && (this.getLogisticsId() == null ? other.getLogisticsId() == null : this.getLogisticsId().equals(other.getLogisticsId()))
            && (this.getLogisticsNumber() == null ? other.getLogisticsNumber() == null : this.getLogisticsNumber().equals(other.getLogisticsNumber()))
            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()))
            && (this.getCodconfirmTime() == null ? other.getCodconfirmTime() == null : this.getCodconfirmTime().equals(other.getCodconfirmTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_base
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getOrderType() == null) ? 0 : getOrderType().hashCode());
        result = prime * result + ((getSellerId() == null) ? 0 : getSellerId().hashCode());
        result = prime * result + ((getSellerName() == null) ? 0 : getSellerName().hashCode());
        result = prime * result + ((getMemberId() == null) ? 0 : getMemberId().hashCode());
        result = prime * result + ((getMemberName() == null) ? 0 : getMemberName().hashCode());
        result = prime * result + ((getOrderState() == null) ? 0 : getOrderState().hashCode());
        result = prime * result + ((getMoneyOrder() == null) ? 0 : getMoneyOrder().hashCode());
        result = prime * result + ((getDownpaymentAmount() == null) ? 0 : getDownpaymentAmount().hashCode());
        result = prime * result + ((getMonthlyAmount() == null) ? 0 : getMonthlyAmount().hashCode());
        result = prime * result + ((getDeliverTime() == null) ? 0 : getDeliverTime().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getCodconfirmRemark() == null) ? 0 : getCodconfirmRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getIsFullPayment() == null) ? 0 : getIsFullPayment().hashCode());
        result = prime * result + ((getPickingTime() == null) ? 0 : getPickingTime().hashCode());
        result = prime * result + ((getSupplier() == null) ? 0 : getSupplier().hashCode());
        result = prime * result + ((getStagingMoney() == null) ? 0 : getStagingMoney().hashCode());
        result = prime * result + ((getLogisticsName() == null) ? 0 : getLogisticsName().hashCode());
        result = prime * result + ((getLogisticsId() == null) ? 0 : getLogisticsId().hashCode());
        result = prime * result + ((getLogisticsNumber() == null) ? 0 : getLogisticsNumber().hashCode());
        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
        result = prime * result + ((getCodconfirmTime() == null) ? 0 : getCodconfirmTime().hashCode());
        return result;
    }
}