package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.CallAssetsOperationLog;
import com.jzfq.retail.bean.domain.CallAssetsOperationLogQuery;
import com.jzfq.retail.bean.domain.CallAssetsOperationLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CallAssetsOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int countByExample(CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int deleteByExample(CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int insert(CallAssetsOperationLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int insertSelective(CallAssetsOperationLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    List<CallAssetsOperationLogWithBLOBs> selectByExampleWithBLOBs(CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    List<CallAssetsOperationLog> selectByExample(CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") CallAssetsOperationLogWithBLOBs record, @Param("example") CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CallAssetsOperationLogWithBLOBs record, @Param("example") CallAssetsOperationLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_assets_operation_log
     *
     * @mbggenerated Thu Jul 19 14:38:18 CST 2018
     */
    int updateByExample(@Param("record") CallAssetsOperationLog record, @Param("example") CallAssetsOperationLogQuery example);
}