package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.CustomerCouponRecord;
import com.jzfq.retail.bean.domain.CustomerCouponRecordQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerCouponRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int countByExample(CustomerCouponRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int deleteByExample(CustomerCouponRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int insert(CustomerCouponRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int insertSelective(CustomerCouponRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    List<CustomerCouponRecord> selectByExample(CustomerCouponRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    CustomerCouponRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustomerCouponRecord record, @Param("example") CustomerCouponRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int updateByExample(@Param("record") CustomerCouponRecord record, @Param("example") CustomerCouponRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int updateByPrimaryKeySelective(CustomerCouponRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon_record
     *
     * @mbggenerated Wed Aug 15 16:47:45 CST 2018
     */
    int updateByPrimaryKey(CustomerCouponRecord record);
}