package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.ErrorRetryTask;
import com.jzfq.retail.bean.domain.ErrorRetryTaskQuery;
import com.jzfq.retail.bean.domain.ErrorRetryTaskWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ErrorRetryTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int countByExample(ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int deleteByExample(ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int insert(ErrorRetryTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int insertSelective(ErrorRetryTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    List<ErrorRetryTaskWithBLOBs> selectByExampleWithBLOBs(ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    List<ErrorRetryTask> selectByExample(ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    ErrorRetryTaskWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErrorRetryTaskWithBLOBs record, @Param("example") ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ErrorRetryTaskWithBLOBs record, @Param("example") ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByExample(@Param("record") ErrorRetryTask record, @Param("example") ErrorRetryTaskQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByPrimaryKeySelective(ErrorRetryTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ErrorRetryTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_retry_task
     *
     * @mbggenerated Tue Jul 03 17:06:28 CST 2018
     */
    int updateByPrimaryKey(ErrorRetryTask record);
}