package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.GoodsStock;
import com.jzfq.retail.bean.domain.GoodsStockQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int countByExample(GoodsStockQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int deleteByExample(GoodsStockQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int insert(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int insertSelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    List<GoodsStock> selectByExample(GoodsStockQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    GoodsStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsStock record, @Param("example") GoodsStockQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int updateByExample(@Param("record") GoodsStock record, @Param("example") GoodsStockQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Aug 10 20:52:27 CST 2018
     */
    int updateByPrimaryKey(GoodsStock record);
}