package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.GpsCheckRule;
import com.jzfq.retail.bean.domain.GpsCheckRuleQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpsCheckRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int countByExample(GpsCheckRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int deleteByExample(GpsCheckRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int insert(GpsCheckRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int insertSelective(GpsCheckRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    List<GpsCheckRule> selectByExample(GpsCheckRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    GpsCheckRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") GpsCheckRule record, @Param("example") GpsCheckRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int updateByExample(@Param("record") GpsCheckRule record, @Param("example") GpsCheckRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int updateByPrimaryKeySelective(GpsCheckRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_check_rule
     *
     * @mbggenerated Mon Aug 06 19:17:55 CST 2018
     */
    int updateByPrimaryKey(GpsCheckRule record);
}