package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.OrderPayCashLog;
import com.jzfq.retail.bean.domain.OrderPayCashLogQuery;
import com.jzfq.retail.bean.domain.OrderPayCashLogWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderPayCashLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int countByExample(OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int deleteByExample(OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int insert(OrderPayCashLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int insertSelective(OrderPayCashLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    List<OrderPayCashLogWithBLOBs> selectByExampleWithBLOBs(OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    List<OrderPayCashLog> selectByExample(OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    OrderPayCashLogWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderPayCashLogWithBLOBs record, @Param("example") OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") OrderPayCashLogWithBLOBs record, @Param("example") OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByExample(@Param("record") OrderPayCashLog record, @Param("example") OrderPayCashLogQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByPrimaryKeySelective(OrderPayCashLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(OrderPayCashLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay_cash_log
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByPrimaryKey(OrderPayCashLog record);
}