package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.PurchaseCollectGoodsInfo;
import com.jzfq.retail.bean.domain.PurchaseCollectGoodsInfoQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PurchaseCollectGoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int countByExample(PurchaseCollectGoodsInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int deleteByExample(PurchaseCollectGoodsInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int insert(PurchaseCollectGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int insertSelective(PurchaseCollectGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    List<PurchaseCollectGoodsInfo> selectByExample(PurchaseCollectGoodsInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    PurchaseCollectGoodsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurchaseCollectGoodsInfo record, @Param("example") PurchaseCollectGoodsInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByExample(@Param("record") PurchaseCollectGoodsInfo record, @Param("example") PurchaseCollectGoodsInfoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByPrimaryKeySelective(PurchaseCollectGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods_info
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByPrimaryKey(PurchaseCollectGoodsInfo record);
}