package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.PurchaseCollectGoods;
import com.jzfq.retail.bean.domain.PurchaseCollectGoodsQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PurchaseCollectGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int countByExample(PurchaseCollectGoodsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int deleteByExample(PurchaseCollectGoodsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int insert(PurchaseCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int insertSelective(PurchaseCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    List<PurchaseCollectGoods> selectByExample(PurchaseCollectGoodsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    PurchaseCollectGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") PurchaseCollectGoods record, @Param("example") PurchaseCollectGoodsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByExample(@Param("record") PurchaseCollectGoods record, @Param("example") PurchaseCollectGoodsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByPrimaryKeySelective(PurchaseCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_collect_goods
     *
     * @mbggenerated Thu Aug 09 15:38:21 CST 2018
     */
    int updateByPrimaryKey(PurchaseCollectGoods record);
}