package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.RemittanceAccount;
import com.jzfq.retail.bean.domain.RemittanceAccountQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RemittanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int countByExample(RemittanceAccountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int deleteByExample(RemittanceAccountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int insert(RemittanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int insertSelective(RemittanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    List<RemittanceAccount> selectByExample(RemittanceAccountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    RemittanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") RemittanceAccount record, @Param("example") RemittanceAccountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByExample(@Param("record") RemittanceAccount record, @Param("example") RemittanceAccountQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByPrimaryKeySelective(RemittanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remittance_account
     *
     * @mbggenerated Wed Jun 27 16:29:15 CST 2018
     */
    int updateByPrimaryKey(RemittanceAccount record);
}