package com.jzfq.retail.core.dao;

import com.jzfq.retail.bean.domain.WithdrawRecord;
import com.jzfq.retail.bean.domain.WithdrawRecordQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithdrawRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int countByExample(WithdrawRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int deleteByExample(WithdrawRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int insert(WithdrawRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int insertSelective(WithdrawRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    List<WithdrawRecord> selectByExample(WithdrawRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    WithdrawRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") WithdrawRecord record, @Param("example") WithdrawRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int updateByExample(@Param("record") WithdrawRecord record, @Param("example") WithdrawRecordQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int updateByPrimaryKeySelective(WithdrawRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_record
     *
     * @mbggenerated Fri Aug 31 15:56:25 CST 2018
     */
    int updateByPrimaryKey(WithdrawRecord record);
}